name: generate

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make output
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - run: make install-go deps build-and-run setup-git commit
      env:
        GIT_NAME: Max Gonzih via GH Actions
        GIT_EMAIL: gonzih@gmail.com
