name: generate

on:
  push:
    branches:
    - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make output
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - run: make install-go deps build-and-run
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
    - run: make setup-git commit
      env:
        GIT_NAME: Max Gonzih via GH Actions
        GIT_EMAIL: gonzih@gmail.com
